# Generated by Django 3.0.5 on 2020-10-07 13:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_perfil', models.ImageField(blank=True, db_column='imagen', default='perfil/avatar-no-img.webp', null=True, upload_to='perfil')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('seguidores', models.ManyToManyField(blank=True, related_name='seguidor', to='web.Prueba')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'prueba',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
