# Generated by Django 3.0.5 on 2020-10-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201014_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='p',
        ),
    ]
