# Generated by Django 3.0.5 on 2020-05-01 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_auto_20200501_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recetas_Guardadas',
            new_name='Receta_Guardada',
        ),
    ]
