# Generated by Django 3.0.5 on 2020-05-10 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_auto_20200501_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso',
            name='posicion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='receta_guardada',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardadas', to='web.Receta'),
        ),
        migrations.AlterField(
            model_name='receta_guardada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_guardadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
