# Generated by Django 3.0.5 on 2020-10-18 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201016_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente_receta',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recetas', to='web.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recetas', to='web.Categoria'),
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificacion',
        ),
        migrations.AlterModelTable(
            name='receta_guardada',
            table='receta_guardada',
        ),
    ]
