# Generated by Django 3.0.5 on 2020-05-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200511_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='sugerencia',
            table='sugerencia',
        ),
    ]
