# Generated by Django 3.0.5 on 2020-05-21 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0006_auto_20200515_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente_receta',
            name='unidad_medida',
            field=models.ForeignKey(default=1, on_delete=models.SET('Otros'), to='web.Unidad_medida'),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='tipo',
            field=models.CharField(choices=[('cat', 'Categoria'), ('udm', 'Unidad de medida')], default=('cat', 'Categoria'), max_length=3),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('visto', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('comentario', 'Comentario'), ('respuesta', 'Respuesta'), ('valoracion', 'Valoracion'), ('siguiendo', 'Siguiendo')], default=('comentario', 'Comentario'), max_length=20)),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('usuario_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
