# Generated by Django 3.0.5 on 2020-09-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200929_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Comentario'),
        ),
    ]
