# Generated by Django 3.0.5 on 2020-09-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_notificacion_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='caso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Comentario'),
        ),
    ]
