# Generated by Django 3.0.5 on 2020-09-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20200929_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='comentario',
        ),
    ]
