# Generated by Django 3.0.5 on 2020-09-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_notificacion_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='caso',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Receta'),
        ),
    ]
