# Generated by Django 3.0.5 on 2020-09-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20200929_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Comentario'),
        ),
    ]
